architecture: minicpm
model_path: openbmb/MiniCPM-o-2_6
dataset:
  - dataset_path: compling/CLEVR_categories
  - dataset_split: color
forward:
  - max_new_tokens: 1
output_db: minicpm-o-coco.db
model:
  - torch_dtype: auto
  - trust_remote_code: True
  - attn_implementation: sdpa
pooled_output: True
modules:
  - llm.model.layers.13.post_attention_layernorm
  - llm.model.layers.27.post_attention_layernorm
