architecture: llavanext
model_path: llava-hf/llama3-llava-next-8b-hf
input_dir: ./data/test-images/
prompt: "Describe the color in this image in one word."
output_db: output/llama3-llava-next-8b-hf.db
pooling_method: mean
modules:
  - language_model.*
