architecture: llavanext
model_path: llava-hf/llava-v1.6-mistral-7b-hf
input_dir: ./data/test-images/
prompt: "Describe the color in this image in one word."
output_db: output/llava-v1.6-mistral-7b-hf.db
pooling_method: mean
modules:
  - language_model.*
