architecture: llava
model_path: llava-hf/llava-1.5-7b-hf
dataset:
  - dataset_path: compling/CLEVR_categories
  - dataset_split: boolean
output_db: output/llava-boolean.db
pooling_method: mean
modules:
  - language_model.model.layers.16.post_attention_layernorm
  - language_model.model.layers.31.post_attention_layernorm
