architecture: blip2
model_path: Salesforce/blip2-opt-2.7b
dataset:
  - dataset_path: compling/CLEVR_categories
  - dataset_split: color
output_db: output/blip2-clevr.db
pooled_output: True
modules:
  - language_model.model.decoder.layers.16.self_attn_layer_norm
  - language_model.model.decoder.layers.31.self_attn_layer_norm
