architecture: minicpm
model_path: compling/MiniCPM-V-2
dataset:
  - dataset_path: compling/CLEVR_categories
  - dataset_split: color
model:
  - torch_dtype: auto
  - trust_remote_code: True
forward:
  - max_new_tokens: 1
output_db: output/minicpm-V2-clevr.db
pooling_method: mean
modules:
  - llm.model.layers.19.post_attention_layernorm
  - llm.model.layers.39.post_attention_layernorm
