architecture: llava
model_path: llava-hf/bakLlava-v1-hf
input_dir: ./data/test-images/
prompt: "Describe the color in this image in one word."
output_db: output/bakLlava-v1-hf.db
modules:
  - language_model.*
