architecture: cogvlm
model_path: THUDM/cogvlm-chat-hf
model:
  - low_cpu_mem_usage: True
  - trust_remote_code: True
forward:
  - max_new_tokens: 2048
  - do_sample: False
output_db: cogvlm.db
input_dir: ./data/
prompt: "Describe the color in this image in one word."
modules:
  - model.layers.*.self_attn
