architecture: glamm
model_path: MBZUAI/GLaMM-FullScope
model:
  - torch_dtype: auto
output_db: glamm.db
input_dir: ./data/
prompt: "Describe the color in this image in one word."
modules:
  - multi_modal_projector
  - language_model.lm_head
