architecture: janus
model_path: deepseek-community/Janus-Pro-1B
model:
  - attn_implementation: eager
output_db: janus.db
input_dir: ./data
prompt: "Describe the color in this image in one word."
modules:
  - model.language_model.layers.11.post_attention_layernorm
  - model.language_model.layers.23.post_attention_layernorm
