architecture: llava
model_path: llava-hf/llava-1.5-7b-hf
model:
  - torch_dtype: auto
output_dir: ./output_dir/
input_dir: ./data/
prompt: "Describe the color in this image in one word."
modules:
  - language_model.model
  - vision_tower.vision_model.encoder.layers.23
