architecture: minicpm_o
model_path: openbmb/MiniCPM-o-2_6
model:
  - torch_dtype: auto
  - trust_remote_code: True
output_db: minicpm-o.db
input_dir: ./data/
prompt: "Describe the color in this image in one word."
modules:
  - llm.lm_head
  - vpm.encoder.layers.26