architecture: paligemma
model_path: google/paligemma-3b-mix-224
model:
  - torch_dtype: auto
  - token: "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"
output_db: paligemma.db
input_dir: ./data/
prompt: "Describe the color in this image in one word."
modules:
  - language_model.lm_head
  - multi_modal_projector
