architecture: pixtral
model_path: mistralai/Pixtral-12B-2409
input_dir: ./data/
prompt: "Describe the color in this image in one word."
output_db: pixtral.db
modules:
  - layers.19.attention_norm
  - layers.39.attention_norm
download_path: /path/to/your/dir # CHANGE ME
