architecture: plm
model_path: facebook/Perception-LM-1B
model:
  - torch_dtype: auto
  - trust_remote_code: True
forward:
  - max_new_tokens: 1
output_db: output/plm.db
input_dir: ./data/
prompt: "Describe the color in this image in one word."
modules:
  - llm.lm_head
  - vpm.encoder.layers.26
