# Creative Commons Image Downloader Configuration
# This file defines the configuration for downloading images

# Basic Settings
num_images: 10
normalize_size: 256
data_dir: "./data/images/colors/"
results_filename: "colors.json"

# Search Provider Configuration
# Options: google, bing, both
search_provider: "both"
retrieve_multiplier: 10

# Image Processing Settings
image_format: "JPEG"  # JPEG, PNG, WEBP
image_quality: 90
load_truncated_images: true

# Download Settings
max_size_mb: 10
timeout: 15

# Deduplication Settings
enable_deduplication: true
similarity_threshold: 5

# Rate Limiting (seconds)
request_delay_min: 0.5
request_delay_max: 1.5

# Search Queries - Color Concepts
queries:
  - "red"
  - "blue"
  - "yellow"
  - "green"
  # - "orange"
  # - "purple"
  - "white"
  - "black"
  # - "gray"
  # - "silver"
  # - "gold"
  # - "pink"
  # - "brown"
  # - "beige"
  # - "crimson"
  # - "maroon"
  # - "cyan"
  # - "turquoise"
  # - "violet"
  # - "magenta"

# User Agent Rotation
user_agents:
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

# Direct Image Extensions
direct_img_extensions:
  - ".jpg"
  - ".jpeg"
  - ".png"
  - ".gif"
  - ".webp"
  - ".bmp"
  - ".tiff"
