architecture: paligemma
model_path: google/paligemma-3b-mix-224
model:
  - torch_dtype: auto
  - token: <HUGGINGFACE_TOKEN>
output_db: output/paligemma-3b-mix-224.db
input_dir: ./data/test-images/
prompt: "Describe the color in this image in one word."
modules:
  - language_model.lm_head
  - multi_modal_projector
