architecture: qwen
model_path: Qwen/Qwen2-VL-2B-Instruct
dataset:
  - dataset_path: compling/CLEVR_categories
  - dataset_split: boolean
output_db: output/qwen-boolean.db
pooling_method: mean
modules:
  - model.layers.13.post_attention_layernorm
  - model.layers.27.post_attention_layernorm
