architecture: qwen
model_path: Qwen/Qwen2-VL-2B-Instruct
model:
  - torch_dtype: auto
preprocess:
  - resize: True
  - width: 336
  - height: 336
output_db: ../output/Qwen2-VL-2B-Instruct-VisualFlow.db
input_dir: ../data_local/coco/cocoval_50.txt
prompt: "Describe the color in this image in one word."
pooling_method: cls
modules:
  - visual.merger
  - model.layers.27.post_attention_layernorm
  - model.norm

