architecture: qwen
model_path: Qwen/Qwen2-VL-2B-Instruct
model:
  - torch_dtype: auto
output_db: ../output/Qwen2-VL-2B-Instruct-VisualFlow.db
input_dir: ../data/test-images/
prompt: "Describe the color in this image in one word."
pooling_method: cls
modules:
  - visual.blocks.31
  - visual.merger
  - model.layers.27.post_attention_layernorm
  - model.norm
  - lm_head

