architecture: qwen
model_path: Qwen/Qwen2-VL-7B-Instruct
model:
  - torch_dtype: auto
preprocess:
  - resize: True
  - width: 336
  - height: 336
output_db: ../output/Qwen2-VL-7B-Instruct/AttentionValues.db
input_dir: ../data_local/coco/cocoval_50.txt
prompt: "Describe this image in one sentence."
pooling_method: None
modules:
  - visual.blocks.\d{1,2}.attn.qkv
  - visual.merger
  - model.layers.\d{1,2}.self_attn.v_proj
  - model.norm

